# Generated by Django 3.2.25 on 2024-04-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0002_debitnoteitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='returndate',
        ),
    ]
