# Generated by Django 3.2.25 on 2024-05-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_auto_20240430_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnotereference',
            name='credit_note',
        ),
    ]
