# Generated by Django 3.2.25 on 2024-05-03 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_remove_creditnotereference_credit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions_party',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
    ]
