# Generated by Django 3.2.25 on 2024-05-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_auto_20240504_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stockIn',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stockOut',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
